### ISSUE TITLE
question: flowable designer vs eclipse bpmn2

### ISSUE THREAD

**Issue by n0mer** [flowable/flowable-designer#13]
Hello,

quick question: what is recommended way to create BPMN2 files?

https://www.eclipse.org/bpmn2-modeler/ - works for Oxygen 4.7, last updated December 15, 2017.

Flowable designer works only for Mars 4.5 and Neon 4.6, and was last updated Nov 1, 2016 (and i doubt it support Flowable 6.x features).

**Comment by tijsrademakers** [comment]
For questions it's best to use the forum (https://forum.flowable.org).
The Designer can be used indeed, but there's also the web based Modeler that's part of the Flowable download package.

**Comment by n0mer** [comment]
@tijsrademakers sure: https://forum.flowable.org/t/eclipse-bpmn2-modeler-applicability/1663
