### ISSUE TITLE
update site link to install eclipse flowable-designer its broken.

### ISSUE THREAD

**Issue by christianvalverdevalverde** [flowable/flowable-designer#9]
please fix it

**Comment by yvoswillens** [comment]
The update site link is working.
It's supposed to be used from within Eclipse (as described in the docs).
When opened with a browser it will result in a 404 because the folder has no index.html.

if it's not working when used in Eclipse please leave a comment.

Regards,

Yvo

**Comment by n0mer** [comment]
it is not working right now - see https://github.com/flowable/flowable-engine/issues/815
